Follow test failures

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -42,9 +42,12 @@ test: $(PROG)
 	@mkdir -p failures
 	@rm -f failures/*
 	@echo Running tests:
+	@rm -f *.err
 	@for prog in $(PROG); do \
-	./$$prog; \
-	done
+		( ./$$prog || touch $$prog.err ) ; \
+	 done
+	@test `find . -name \*.err | wc -l` = "0" || ( echo ; echo "The following tests have errors:" ; \
+	   for i in *.err ; do echo `basename $$i .err`; done ; rm -f *.err ; false ) 
 
 $(PROG) : % : %.cpp Makefile ../timeseries.so
 	$(CC) $(CFLAGS) -o $@ $@.cpp $(INCLUDES) $(LIBS)
